// Autogenerated file.
// DO NOT EDIT. ANY CHANGES WILL BE OVERWRITTEN

import { EventNames } from './all_event_names';
import {
    ProgressBar,
    Gui,
    EngineTXD,
    EngineDFF,
    EngineCOL,
    EngineIFP,
    PrimitiveType,
    DxTexture,
    ObjectGroup,
    Browser,
    Light,
    Effect,
    Searchlight,
    Weapon,
    GuiBrowser,
    GuiMemo,
    GuiElement,
    GuiEdit,
    GuiScrollBar,
    GuiWindow,
    Projectile,
    Material,
    Svg,
    SvgCallback,
    Userdata,
    TextItem,
    Pickup,
    Request,
    Player,
    Blip,
    ColShape,
    Element,
    Ped,
    Resource,
    Team,
    Vehicle,
    XmlNode,
    File,
    Marker,
    MTASAObject,
    RadarArea,
    Water,
    Timer,
    HandleFunction,
    TimerCallbackFunction,
    FetchRemoteCallback,
    GenericEventHandler,
    CommandHandler,
    BindKeyCallback,
    BindKeyCallbackVarArgs,
    ControlName,
    KeyName,
    KeyState,
    Vector2,
    Vector3,
    Vector4,
    Matrix,
} from '../structure';

export interface OnClientElementColShapeHit extends GenericEventHandler {
    name: EventNames.OnClientElementColShapeHit;
    function: (
        this: void,
        theShape: ColShape,
        matchingDimension: boolean,
    ) => void;
}

export interface OnClientElementColShapeLeave extends GenericEventHandler {
    name: EventNames.OnClientElementColShapeLeave;
    function: (
        this: void,
        theShape: ColShape,
        matchingDimension: boolean,
    ) => void;
}

export interface OnClientElementDataChange extends GenericEventHandler {
    name: EventNames.OnClientElementDataChange;
    function: (
        this: void,
        theKey: string,
        oldValue: unknown,
        newValue: unknown,
    ) => void;
}

export interface OnClientElementDestroy extends GenericEventHandler {
    name: EventNames.OnClientElementDestroy;
    function: (this: void) => void;
}

export interface OnClientElementDimensionChange extends GenericEventHandler {
    name: EventNames.OnClientElementDimensionChange;
    function: (this: void, oldDimension: number, newDimension: number) => void;
}

export interface OnClientElementInteriorChange extends GenericEventHandler {
    name: EventNames.OnClientElementInteriorChange;
    function: (this: void, oldInterior: number, newInterior: number) => void;
}

export interface OnClientElementModelChange extends GenericEventHandler {
    name: EventNames.OnClientElementModelChange;
    function: (this: void, oldModel: number, newModel: number) => void;
}

export interface OnClientElementStreamIn extends GenericEventHandler {
    name: EventNames.OnClientElementStreamIn;
    function: (this: void) => void;
}

export interface OnClientElementStreamOut extends GenericEventHandler {
    name: EventNames.OnClientElementStreamOut;
    function: (this: void) => void;
}
