// Autogenerated file.
// DO NOT EDIT. ANY CHANGES WILL BE OVERWRITTEN

import {
    ProgressBar,
    Gui,
    EngineTXD,
    EngineDFF,
    EngineCOL,
    EngineIFP,
    PrimitiveType,
    Texture,
    ObjectGroup,
    Matrix,
    Browser,
    Light,
    Effect,
    Searchlight,
    Weapon,
    GuiBrowser,
    GuiElement,
    GuiEdit,
    GuiScrollBar,
    GuiWindow,
    Projectile,
    Material,
    Userdata,
    TextItem,
    Pickup,
    Request,
    Player,
    Blip,
    ColShape,
    Element,
    Ped,
    Resource,
    Team,
    Vehicle,
    XmlNode,
    File,
    Marker,
    MTASAObject,
    RadarArea,
    Water,
    Timer,
    HandleFunction
} from '../../structure';

/** @customConstructor GuiMemo */
export class GuiMemo extends GuiElement {
    /**
     * This function allows you to set or remove read-only status for a GUI memo. If read-only
     * is set to true, the contents are not editable.
     */
    readOnly: boolean;

    /**
     * This function allows you to set or remove read-only status for a GUI memo. If read-only
     * is set to true, the contents are not editable.
     * @see {@link https://wiki.multitheftauto.com/wiki/GuiMemoSetReadOnly Wiki, guiMemoSetReadOnly }
     * @return returns true if the status was successfully changed, false otherwise.
     */
    setReadOnly(): boolean;
}
