export type Table = any;
export type Userdata = any;
export type TextItem = Userdata;
export type ProgressBar = Userdata;
export type Pickup = Userdata;
export type Gui = Userdata;
export type Txd = Userdata;
export type Dff = Userdata;
export type Col = Userdata;
export type Ifp = Userdata;
export type PrimitiveType = Userdata;
export type GuiScrollBar = Userdata;
export type Texture = Userdata;
export type ObjectGroup = Userdata;
export type Request = Userdata;
export type Matrix = any;

export { Player } from 'types/mtasa/client/oop/Player';
export { Blip } from 'types/mtasa/client/oop/Blip';
export { ColShape } from 'types/mtasa/client/oop/ColShape';
export { Element } from 'types/mtasa/client/oop/Element';
export { Ped } from 'types/mtasa/client/oop/Ped';
export { Resource } from 'types/mtasa/client/oop/Resource';
export { Team } from 'types/mtasa/client/oop/Team';
export { Vehicle } from 'types/mtasa/client/oop/Vehicle';
export { XmlNode } from 'types/mtasa/client/oop/XmlNode';
export { File } from 'types/mtasa/client/oop/File';
export { Marker } from 'types/mtasa/client/oop/Marker';
export { RadarArea } from 'types/mtasa/client/oop/RadarArea';
export { Water } from 'types/mtasa/client/oop/Water';
export { Timer } from 'types/mtasa/client/oop/Timer';
export { Browser } from 'types/mtasa/client/oop/Browser';
export { Light } from 'types/mtasa/client/oop/Light';
export { Effect } from 'types/mtasa/client/oop/Effect';
export { Searchlight } from 'types/mtasa/client/oop/Searchlight';
export { Weapon } from 'types/mtasa/client/oop/Weapon';
export { GuiBrowser } from 'types/mtasa/client/oop/GuiBrowser';
export { GuiMemo } from 'types/mtasa/client/oop/GuiMemo';
export { Projectile } from 'types/mtasa/client/oop/Projectile';

export type HandleFunction = any;
