export type Table = any;
export type Userdata = any;
export type TextItem = Userdata;
export type ProgressBar = Userdata;
export type Pickup = Userdata;
export type Gui = Userdata;
export type Txd = Userdata;
export type Dff = Userdata;
export type Col = Userdata;
export type Ifp = Userdata;
export type PrimitiveType = Userdata;
export type GuiScrollBar = Userdata;
export type Texture = Userdata;
export type ObjectGroup = Userdata;
export type Request = Userdata;
export type Matrix = any;

export { Player } from './oop/Player';
export { Blip } from './oop/Blip';
export { ColShape } from './oop/ColShape';
export { Element } from './oop/Element';
export { Ped } from './oop/Ped';
export { Resource } from './oop/Resource';
export { Team } from './oop/Team';
export { Vehicle } from './oop/Vehicle';
export { XmlNode } from './oop/XmlNode';
export { File } from './oop/File';
export { Marker } from './oop/Marker';
export { RadarArea } from './oop/RadarArea';
export { Water } from './oop/Water';
export { Timer } from './oop/Timer';
export { Browser } from './oop/Browser';
export { Light } from './oop/Light';
export { Effect } from './oop/Effect';
export { Searchlight } from './oop/Searchlight';
export { Weapon } from './oop/Weapon';
export { GuiBrowser } from './oop/GuiBrowser';
export { GuiMemo } from './oop/GuiMemo';
export { Projectile } from './oop/Projectile';

export type HandleFunction = any;
