// Autogenerated file.
// DO NOT EDIT. ANY CHANGES WILL BE OVERWRITTEN

import {
    ProgressBar,
    Gui,
    EngineTXD,
    EngineDFF,
    EngineCOL,
    EngineIFP,
    PrimitiveType,
    DxTexture,
    ObjectGroup,
    Browser,
    Light,
    Effect,
    Searchlight,
    Weapon,
    GuiBrowser,
    GuiMemo,
    GuiElement,
    GuiEdit,
    GuiScrollBar,
    GuiWindow,
    Projectile,
    Material,
    Svg,
    SvgCallback,
    Userdata,
    TextItem,
    Pickup,
    Request,
    Player,
    Blip,
    ColShape,
    Element,
    Ped,
    Resource,
    Team,
    Vehicle,
    XmlNode,
    File,
    Marker,
    MTASAObject,
    RadarArea,
    Water,
    Timer,
    HandleFunction,
    TimerCallbackFunction,
    FetchRemoteCallback,
    GenericEventHandler,
    CommandHandler,
    BindKeyCallback,
    BindKeyCallbackVarArgs,
    ControlName,
    KeyName,
    KeyState,
    Vector2,
    Vector3,
    Vector4,
    Matrix,
} from '../structure';

/**
 * Creates an explosion of a certain type at a specified point in the world. If creator is
 * specified, the explosion will occur only in its dimension.
 * @see https://wiki.multitheftauto.com/wiki/CreateExplosion
 * @param x a float value that specifies the X world coordinate where the explosion is created at.
 * @param y a float value that specifies the Y world coordinate where the explosion is created at.
 * @param z a float value that specifies the Z world coordinate where the explosion is created at.
 * @param theType a integer specifying the explosion type. Valid types are:
 * @param makeSound a boolean specifying whether the explosion should be heard or not.
 * @param camShake a float specifying the camera shakes intensity.
 * @param damaging a boolean specifying whether the explosion should cause damage or not.
 * @noSelf
 */
export declare function createExplosion(
    x: number,
    y: number,
    z: number,
    theType: number,
    makeSound?: boolean,
    camShake?: number,
    damaging?: boolean,
): boolean;
