name: NPM Package

on:
    pull_request:
        paths-ignore:
            - '**.md'
    push:
        paths-ignore:
            - '**.md'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node 12
              uses: actions/setup-node@v3.0.0
              with:
                  node-version: 12.x
            - name: Cache Node files
              uses: actions/cache@v3.0.2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: |
                      ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - run: npm ci
            - run: npm run test
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node 12
              uses: actions/setup-node@v3.0.0
              with:
                  node-version: 12.x
            - name: Cache Node files
              uses: actions/cache@v3.0.2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: |
                      ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - run: npm ci
            - run: npm run build
    publish:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        needs:
            - build
            - test
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3.0.0
              with:
                  node-version: '12.x'
                  registry-url: 'https://registry.npmjs.org'
            - name: Cache Node files
              uses: actions/cache@v3.0.2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: |
                      ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - run: npm ci
            - run: npm run build
            - run: |
                  export TAG="latest"
                  npm publish --tag "$TAG"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
